services:
  database:
    container_name: db
    image: postgres
    volumes:
      - "pgdata:/var/lib/postgresql:/data"
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHEL", "pg_isready"]
        interval: 5s
        timeout: 5s
        retris: 10
    restart: always

  api:
    container_name: api
    build:
        context: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env
    restart: always
    
volumes:
  pgdata: {}
